[package]
name = "testground"
version = "0.0.1"
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
#[workspace]

[lib]
name = "testground"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
#shrinkwraprs = "=0.3.0"
#chrono = "=0.4.19"
serde = { version = "=1.0.123", default-features = false }
#strum = "=0.19"
#strum_macros = "=0.19"
#derive_more = "=0.99.16"
#bincode = "=1.3.3"
#base64 = {version = "0.13"}

#snapmail_proc_macro = {path = "../../crates/proc_macro", default-features = false }

# online
hdk = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "hdk", default-features = false }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holo_hash", default-features = false }

# local
#hdk = { path = "../../../holochain-develop/crates/hdk" }
#holo_hash = { path = "../../../holochain-develop/crates/holo_hash" }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
thiserror = "1.0.24"

# online
holochain_serialized_bytes = "=0.0.51"
holochain = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain", default-features = false, features = ["only_check_wasms"] }
holochain_util = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain_util", default-features = false }
holochain_conductor_api = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain_conductor_api", default-features = false }

# local
#holochain = { path = "../../../holochain-develop/crates/holochain" }
#holochain_util = { path = "../../../holochain-develop/crates/holochain_util" }
#holochain_conductor_api = { path = "../../../holochain-develop/crates/holochain_conductor_api" }

