[package]
name = "testground_sweettest"
version = "0.0.1"
edition = "2018"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
shrinkwraprs = { version = "0.3.0", default-features = false }
chrono = { version = "=0.4.19", default-features = false }
serde = { version = "1.0", default-features = false }
strum = { version = "0.19", default-features = false }
strum_macros = { version = "0.19", default-features = false }
derive_more = { version = "=0.99.16", default-features = false }
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
colored = "2.0.0"
futures = { version = "0.3.1", default-features = false }

tokio = { version = "1.3", features = [ "full" ] }
tokio-stream = { version = "0.1", default-features = false }
maplit = { version = "1", default-features = false }

testground = { path = "../zome", default-features = false }

# online
holochain = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain", default-features = false, features = ["test_utils"] }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holo_hash", default-features = false  }
holochain_zome_types = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain_zome_types", default-features = false  }
kitsune_p2p = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "kitsune_p2p", default-features = false  }
holochain_state = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain_state", default-features = false  }
holochain_p2p = { git = "https://github.com/holochain/holochain.git", rev = "b2159249935c30ee641cc60a6fa52d29454b1173", package = "holochain_p2p", default-features = false  }

# local
#holochain = { path = "../../holochain-develop/crates/holochain" }
#holo_hash = { path = "../../holochain-develop/crates/holo_hash" }
#holochain_state = { path = "../../holochain-develop/crates/holochain_state" }
#holochain_zome_types = { path = "../../holochain-develop/crates/holochain_zome_types" }
#kitsune_p2p = { path = "../../holochain-develop/crates/kitsune_p2p/kitsune_p2p" }
#holochain_p2p = { path = "../../holochain-develop/crates/holochain_p2p" }

